blog/urls.py
from django.conf.urls import url

from blog import views


app_name = 'blog'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='post_list'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^(?P<slug>[^/]+)/$', views.PostDetail.as_view(), name='post_detail'),
]

rvw_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin


from blog.views import HomePageTemplate


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageTemplate.as_view(), name='home_page'),
]

urlpatterns += [
    url(r'^blog/', include('blog.urls')),
]

blog/models.py
from string import ascii_letters
from random import choice
from django.db import models
from django.urls import reverse

from ckeditor.fields import RichTextField


def slug_uniquify(slug):
    qs = Post.objects.filter(slug=slug)
    if qs.exists():
        while True:
            slug = slug + '-' + choice(ascii_letters)
            if not qs.filter(slug=slug).exists():
                break
    return slug

def bangla_slugify(text):
    first_ten_word = text.split()[:10]
    slug = '-'.join(first_ten_word)
    unique_slug = slug_uniquify(slug)

    return unique_slug


class Post(models.Model):
    title    = models.CharField(max_length=200)
    slug     = models.SlugField(allow_unicode=True, blank=True)
    content  = RichTextField()
    created  = models.DateTimeField(auto_now=True)
    updated  = models.DateTimeField(auto_now_add=True)
    is_draft = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'slug':self.slug})

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug:
            slug = bangla_slugify(self.slug)
        else:
            slug = bangla_slugify(self.title)

        self.slug = slug
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created', '-updated']

blog/forms.py
from django import forms


class MessageForm(forms.Form):
    body = forms.CharField(
        widget=forms.Textarea(
            attrs={'class':'card mb-3',
                  'placeholder':'''পরিচয় গোপন করে সরাসরি বার্তা পাঠাতে এখানে লিখেই সেন্ড করুন। 
অবশ্য যদি কোন উত্তর বা রিপ্লাই আশা করেন তাহলে আপনার ইমেইল আইডিও এখানে দিতে পারেন। ''',
                   }
        ), required=True)

blog/views.py
from concurrent.futures import ThreadPoolExecutor

from django.shortcuts import render,HttpResponse
from django.views.generic import TemplateView, ListView, DetailView
from django.core.mail import send_mail

from blog.models import Post
from .forms import MessageForm


executor = ThreadPoolExecutor(10)


class HomePageTemplate(TemplateView):
    template_name = 'blog/home_page.html'


class PostList(ListView):
    model = Post
    paginate_by = 3
    context_object_name = 'post_list'
    template_name = 'blog/post_list.html'


class PostDetail(DetailView):
    model = Post
    slug_url_kwarg = 'slug'
    template_name = 'blog/post_detail.html'

def contact(request):
    if request.method == "POST":
        form = MessageForm(request.POST)
        sent = False
        if form.is_valid():

            kwargs = {}
            kwargs['subject'] = "MESSAGE FROM MY WEBSITE"
            kwargs['message']  = form.cleaned_data.get('body','no message body found')
            kwargs['from_email'] = 'o1935926686@gmail.com'
            kwargs['recipient_list'] = ['rb60041@gmail.com']
            kwargs['fail_silently'] = False

            sent = executor.submit(send_mail, **kwargs)

            if sent:
                sent=True
        return render(request, 'blog/contact_page.html', {'sent':sent, 'form':form})

    else:
        form = MessageForm()
    return render(request, 'blog/contact_page.html', {'form':form})

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="bn">
<head>
    <!-- MetaData -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Rabiul-Islam">

    <title>{% block title %}Welcome to Rabiuls Virtual World!{% endblock %}</title>

    <!-- Favicon icon -->
    <link rel="icon" type="image/x-icon" href="{% static 'blog/img/favicon.ico' %}"/>

    <!-- Input:CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/intro.css' %}"/>
    <!-- EndInput -->
</head>

<body>
    {% block content %}
    {% endblock %}

    {% block javascript %}
    {% endblock %}
</body>
</html>

blog/templates/blog/contact_page.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% if sent %}
                    <h3 class="w3-panel w3-green w3-card-4 wc-center">আপনার বার্তাটি সফলভাবে প্রেরিত হয়েছে!<br/>
                        <a href="/">হোম পেজ</a>.</h3>
                    <hr/>
                {% endif %}

                {% if sent == False %}
                    <h3 class="w3-panel w3-yellow w3-card-4 wc-center">আপনার বার্তাটি প্রেরন করা যায়নি। আবার
                        চেষ্টা
                        করুন অথাবা <a href="http://fb.com/rabiulislam993">সরাসরি যোগাযোগ করুন</a>।</h3>
                    <hr/>
                {% endif %}

                <br/>
                <form method="POST">
                    <div class="card">
                        {{ form.body }}
                        {% csrf_token %}<br/>
                        <button class="btn btn-outline-dark"><input type="submit" value="send"/></button>
                    </div>
                </form>
                <hr/>
                <br/>
                <div>
                    <p><b>Email: </b>rabiulislam993@live.com</p>
                    <p><b>Github: </b>https://github.com/rabiulislam993/</p>
                    <p><b>Facebook: </b>https://www.facebook.com/Rabiul.Islam.993</p>
                </div>


                <hr/>
                <br/>
                <br/>
                {% include 'blog/snippets/nav_links.html' %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/home_page.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <div class="cover-wrapper">
        <div class="cover">
            <h2 class="big-txt">আহলান ওয়া সাহলান!</h2>
            <h2 class="banner-headline">রবিউল ইসলামের ভার্চুয়াল দুনিয়ায় আপনাকে স্বাগতম!</h2>

            {% include 'blog/snippets/nav_links.html' %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <!-- Input:js -->
    <script src="{% static 'blog/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'blog/js/ripple.min.js' %}"></script>
    <script src="{% static 'blog/js/wow.min.js' %}"></script>
    <script src="{% static 'blog/js/intro.js' %}"></script>
    <!-- EndInput -->
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load disqus_tags %}
{% disqus_dev %}

{% block content %}
    <div class="container">
        <div class="row"> 
            <div class="col-md-6 offset-md-3">
                <h1 class="content-title">{{ post.title }}</h1>
                <p>{{ post.content|safe }} </p>



                {% disqus_show_comments %}

                <hr />
                <br />
                <br />
                {% include 'blog/snippets/nav_links.html' %}
            </div>

        </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1>All Posts</h1>

                {% for post in post_list %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <h4 class="card-title">{{ post.title }}</h4>
                            <small>{{ post.created|timesince }} ago</small>
                            <p class="card-text">
                                {{ post.content|safe|truncatewords:20 }}
                            </p>

                            <a href="{% url 'blog:post_detail' slug=post.slug %}"
                               class="btn btn-outline-dark">Detail</a>
                        </div>
                    </div>
                {% endfor %}

                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}
                            <span class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}

                <hr />
                <br />
                <br />
                {% include 'blog/snippets/nav_links.html' %}

            </div>

        </div>
    </div>

{% endblock %}

blog/templates/blog/snippets/nav_links.html
<div>
    <ul>
        <li><a href="{% url 'blog:post_list' %}">ব্লগ</a></li>
        <li><a href="{% url 'blog:contact' %}">যোগাযোগ</a></li>
        <li><a href="{% url 'blog:post_detail' 'আমি' %}">আমি</a></li>
    </ul>
</div>